- name: "DÉPLOIEMENT COMPLET SERVEUR WEB ASRC — IUC"
  hosts: ec2_server
  become: true
  remote_user: zra-emmanuel

  vars:
    site_dir: /var/www/html
  tasks:  
       # OUVERTURE DU PARE-FEU
    - name: "Autoriser le port 80 (HTTP)"
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: "Autoriser le port 22 (SSH)"
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    # DÉPLOIEMENT DE LA PAGE HTML
    - name: "Suppression de la page Apache par défaut"
      file:
        path: "{{ site_dir }}/index.html"
        state: absent

    - name: "Copie de la page HTML ASRC vers le serveur"
      copy:
        src: /mnt/g/MIKROTIK/aws/index.html
        dest: "{{ site_dir }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: "Définir index.html comme page par défaut Apache"
      lineinfile:
        path: /etc/apache2/mods-enabled/dir.conf
        regexp: 'DirectoryIndex'
        line: '    DirectoryIndex index.html index.html index.cgi index.pl index.xhtml index.htm'
        backrefs: yes

    # REDÉMARRAGE FINAL DES SERVICES
    - name: "Redémarrage d'Apache"
      systemd:
        name: apache2
        state: restarted

    - name: "Redémarrage de MySQL"
      systemd:
        name: mysql
        state: restarted

   
      
